version: 0.8
outputdir: ./bin
scripts:
  fmt: goimports -w src
projects:
  - name: watch
    type: go
    root: src/bin/watch
    imageName: gcr.io/otsimocloud/watch
    dockerfile: ./Dockerfile
    run: ./watch --debug
    develop:
      ports:
        - "30858:18858"
    golang:
      package: bin/watch
      cgoEnabled: false
      ldflags: "-w -X main.Version=${BUILD_VERSION}"
      builder: gb
