#!/bin/bash

DOCKER_IMAGE_NAME=gcr.io/otsimocloud/watch

DOCKER_OLD_IMAGE=$(docker images | grep ${DOCKER_IMAGE_NAME} | tail -n1 | awk '{print $3}')

if [ ${#DOCKER_OLD_IMAGE} -gt 0 ]; then
    docker rmi -f ${DOCKER_OLD_IMAGE}
fi

NUMBER_OF_COMMIT=$(git rev-list HEAD --count)
APP_VERSION=${APP_VERSION:-$(< ./VERSION)}.${NUMBER_OF_COMMIT}
TAG_NAME=${DOCKER_IMAGE_NAME}:${APP_VERSION}

docker build --rm -t ${TAG_NAME} .

if [ "$1" = "push" ]; then
    echo pushing ${TAG_NAME}
    gcloud docker push ${TAG_NAME}
fi